server:
  port: 8881

Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
