server:
  port: 8881
  servlet:
    context-path: /users

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userService?serverTimezone=UTC
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
      compatibility-verifier:
        enabled: false
  config:
    import: optional:configserver:http://localhost:8082
  profiles:
    active: dev
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingCompanyBreaker:
        resisterHeaderIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingCompanyService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s



